In [1]:
import pandas as pd
import numpy as np

NUMPY-> num means 'numeric'  &    py means 'python'

In [2]:
np.array([1,2,3,'hello',56,"samma",2,3])

array(['1', '2', '3', 'hello', '56', 'samma', '2', '3'], dtype='<U11')

In [3]:
type(np.array([1,2,3,'hello',56,"samma",2,3]))  
# always try to create n-dimentional array(1,2,....multi dimention)

numpy.ndarray

In [4]:
#Upcasting

In [5]:
np.array([1,2,3.0])  
# 1,2->int and 3.0-> float 
# but it by default converts the ttype to float 

array([1., 2., 3.])

In [6]:
# Two Dimensions

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
# Minimum dimension 2:

In [9]:
np.array([1,2,3],ndmin=5) # 5 dimension so,5 brackets

array([[[[[1, 2, 3]]]]])

In [10]:
# dtype

In [3]:
np.array([1,2,3],dtype=complex) # convert the datatype

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
# data-type consisting of more than one element:

In [13]:
np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
        #[(a,b),(a,b)] format


array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [14]:
n=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
n[0]

(1, 2)

In [15]:
# <i2  = int16
# <i4  = int 32
# <i8  = int 64

In [16]:
n[0][1]

2

In [17]:
type(n[0][1])

numpy.int64

In [18]:
type(n)

numpy.ndarray

In [19]:
# convert the array to matrix
# matrix is subclass /subset of an array
# its nature like an array

In [20]:
np.mat(np.array([[1,2],[3,4]]))

matrix([[1, 2],
        [3, 4]])

In [21]:
m=np.mat(np.array([[1,2],[3,4]]))
type(m)

numpy.matrix

In [22]:
np.mat(np.array([[1,2],[3,4,5,6]])) # diff dimensions

matrix([[list([1, 2]), list([3, 4, 5, 6])]], dtype=object)

# numpy.asarray

In [65]:
#convert the input to an array
# difference btwn array & asarray is in taking parameters

In [24]:
a=[1,2]
type(a)

list

In [25]:
np.asarray(a)

array([1, 2])

In [26]:
b=[[1,2],[3,4]]
type(b)
np.asarray(b)

array([[1, 2],
       [3, 4]])

In [27]:
np.array(b)

array([[1, 2],
       [3, 4]])

In [28]:
#If dtype is set, array is copied only if dtype does not match:

In [29]:
issubclass(np.matrix, np.ndarray)

True

In [30]:
issubclass(np.ndarray,np.matrix)

False

In [31]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [32]:
np.asarray([1,2]) is a

False

In [33]:
np.array([1,2]) is a

False

# np.asanyarray

In [34]:
# convert to array 
#if & only if the input is not the variance of array
# array format a thaka jabena 
# ex: matrix can't be converted
# list canbe converted

In [42]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [45]:
a = np.mat([1, 2])
a

matrix([[1, 2]])

In [44]:
np.asanyarray([1,2]) is a

False

In [47]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [48]:
y=x

In [49]:
y[1]

2

In [50]:
y[1]=8378538

In [53]:
#This effects the both x & y (hit in same location)

In [51]:
y

array([      1, 8378538,       3])

In [54]:
x

array([      1, 8378538,       3])

In [56]:
# so we need 'copy' function 
# which helps us to do change in x 
# that doesnot make changes in y

In [57]:
z=np.copy(x)

In [58]:
z[0]

1

In [59]:
z[0]=98

In [60]:
z   # modified it

array([     98, 8378538,       3])

In [62]:
x  # but not modified   

array([      1, 8378538,       3])

In [64]:
# it is the main advantage of this 'copy' function
# both x & z are independent with each other
#----->called 'deep copy'
# both x & y are in same location & 
#changes effect both x & y
# dependent on each other
#------>called 'swallow copy' 

# numpy.fromfunction

In [66]:
#Construct an array by executing a function over each coordinate.

In [69]:
np.fromfunction(lambda i,j : i==j,(3,3),dtype=int)
# function->dimension->datatype

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [70]:
np.fromfunction(lambda i,j : i*j,(3,3),dtype=int)


array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [72]:
np.fromfunction(lambda i,j,k : i*j*k ,(3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [73]:
np.fromfunction(lambda i,j,k,m : i*j*k*m ,(1,3,3,3),dtype=int)
#  (3,3,3) for 3 times means 3 dimensions

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [74]:
np.fromfunction(lambda i,j,k,m : i*j*k*m ,(4,3,3,3),dtype=int)
# for 4 times means 4 dimensions

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  3,  6],
         [ 0,  6, 12]],

        [[ 0,  0,  0],
         [ 0,  6, 12],
         [ 0, 12, 24]]]])

In [75]:
np.fromfunction(lambda i,j,k,m : i*j*k*m ,(10,3,3,3),dtype=int)
# for 10 times means 10 dimensions

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  3,  6],
         [ 0,  6, 12]],

        [[ 0,  0,  0],
         [ 0,  6, 12],
         [ 0, 12, 24]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]],

# fromiter

In [76]:
#Create a new 1-dimensional array from an iterable object.

In [77]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x0000028D6E168D48>

In [78]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

# fromstring

In [79]:
a=np.fromstring('234 5678',sep=' ')
a

array([ 234., 5678.])

In [80]:
np.fromstring('1 2',dtype=int,sep=' ')

array([1, 2])

In [82]:
#create record array

In [81]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [86]:
r=np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [87]:
r[1]

(2, 'dd', 2., 2.)

In [89]:
r[1]['a']

2

In [90]:
x1[1]

2

# datatype

In [91]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [92]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [93]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [94]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange & linspace
range-> from python core,takes only integer
arange-> from numpy pakage, takes int,float,

In [95]:
list(range(4,20))

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [96]:
list(range(4,20,2))

[4, 6, 8, 10, 12, 14, 16, 18]

In [98]:
list(range(4.4,20,2))  # error for float

TypeError: 'float' object cannot be interpreted as an integer

In [99]:
## so need 'arange' for float for this above error 

In [100]:
np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [101]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [102]:
np.arange(0,14,3.6)

array([ 0. ,  3.6,  7.2, 10.8])

In [104]:
np.arange(0.1,10,2.5) # it works in every case

array([0.1, 2.6, 5.1, 7.6])

In [109]:
np.arange(16,4,-2)

array([16, 14, 12, 10,  8,  6])

In [113]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [112]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [115]:
# linspace different from range & arange
# here, it will generate 50 data btwn 1 to 5 sequencially

In [114]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [117]:
print((np.linspace(1,5,10)))  # 10 num will generate

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [119]:
print(np.linspace(1,5,10,endpoint=False))
# false means it will go up to  numbers

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]


In [121]:
print(np.linspace(1,5,10,endpoint=True))
# true means it must consider 5 as well

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [124]:
print(np.linspace(1,5,10,axis=0)) 

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [141]:
print(np.linspace(1,5,num=10,axis=0)) 

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [144]:
print(np.linspace(1,3,15,retstep=True)) 
# last num indicates the step number of the result

(array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ]), 0.14285714285714285)


# logspace
Return numbers spaced evenly on a log scale.

In [145]:
np.logspace(2,3,num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [147]:
np.logspace(2,3,num=4,base=2)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [148]:
np.logspace(2,3,num=4,base=3)

array([ 9.        , 12.98024613, 18.72075441, 27.        ])

In [149]:
np.logspace(2,3,num=4,endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

# Matrix creation

In [125]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [127]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [128]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [130]:
np.zeros((3,4,2))
# generate 4*2 for 3 times/dimensions

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [134]:
np.ones((3,2,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [136]:
np.ones((3,5))+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [137]:
np.ones((3,5))*20

array([[20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.]])

In [138]:
np.empty((3,5))  # it will show its previous result

array([[20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.]])

In [139]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [140]:
np.arange(3)

array([0, 1, 2])

# @@@@ class Task @@@

1. 3*4*8 array dimension_ with zeros +5 *2
2. 4 to 8 ,80 such data
3. take list convert those list to matrix
4.array of size 4*5*2 (ones)
show dimension,shape,datatype of that
5.x1=3*3*3
x2=3*3*3
x1+x2

In [155]:
# 1. 3*4*8 array dimension_ with zeros +5 *2
np.zeros((3,4,8))+5*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [156]:
#2. 4 to 8 ,80 such data
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [158]:
# 3. take list convert those list to matrix
a=[[1,2],[7,33]]
np.mat(a)

matrix([[ 1,  2],
        [ 7, 33]])

In [170]:
# 4.array of size 4*5*2 (ones)
# show dimension,shape,datatype of that
b=np.ones((4,5,2))
b.ndim

3

In [169]:
b.shape

(4, 5, 2)

In [171]:
b.dtype

dtype('float64')

In [172]:
#5.x1=3*3*3,x2=3*3*3,x1+x2
x1=np.ones((3,3,3))
x2=np.ones((3,3,3))+5

x1+x2

array([[[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]],

       [[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]],

       [[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]]])