In [2]:
import pandas as pd
import numpy as np

# np.reshape()

In [18]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.arange(16).reshape(1,16)# 1*16
# 2*8 ,8*2,4*4,16*1,1*16 can be shaped

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [20]:
np.arange(16).reshape(2,8) # 2*8

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [21]:
np.arange(16).reshape(8,2) #8*2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [22]:
np.arange(16).reshape(16,1)# 16*1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [23]:
np.arange(16).reshape(4,4)# 4*4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
np.arange(16).reshape(8,2,1)# 8 times of 2*1 (3 dimensions)

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]]])

In [25]:
np.arange(16).reshape(8,2,1,1)# 4 dimensions

array([[[[ 0]],

        [[ 1]]],


       [[[ 2]],

        [[ 3]]],


       [[[ 4]],

        [[ 5]]],


       [[[ 6]],

        [[ 7]]],


       [[[ 8]],

        [[ 9]]],


       [[[10]],

        [[11]]],


       [[[12]],

        [[13]]],


       [[[14]],

        [[15]]]])

In [26]:
np.arange(16).reshape(1,-1) # 1 & understand the other values by default 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [27]:
np.arange(16).reshape(8,-1)# 8 & by defult understand 

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [30]:
np.arange(16).reshape((-1,4)) 
#any negtaive number indicates other numbers by default,
# it can take 4 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
np.arange(16).reshape((-834874,4))
# u can use random negative numbers 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

 # np.diag
 extract the diagonal element of matrix

In [31]:
x=np.arange(16).reshape((-1,4)) # means 4*4
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
np.diag(x)

array([ 0,  5, 10, 15])

In [33]:
y=np.arange(16).reshape((-1,8)) 
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [34]:
np.diag(y)

array([0, 9])

In [36]:
x=np.arange(16).reshape(-1,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
np.diag(x,k=1)

array([ 1,  6, 11])

In [38]:
np.diag(x,k=2)

array([2, 7])

In [39]:
np.diag(x,k=-1)

array([ 4,  9, 14])

In [40]:
np.diag(x,k=-2)

array([ 8, 13])

In [41]:
np.diag(x,k=0) # k=0 by default

array([ 0,  5, 10, 15])

In [42]:
np.diag(x,k=-3)

array([12])

In [44]:
np.diag(x,k=-4) # we dont have any data n that place

array([], dtype=int32)

In [46]:
np.diag(np.diag(x))
# whatever u get from diagonal,it will remain same
# rest one are zeros (means create new with zeros)

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

# np.diagflat
take flattned list ,list of list and create & put them in diagonal

In [47]:
np.diagflat([[1,2],[3,4]]) 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [48]:
np.diagflat([[1,2],[3,4]],k=1) 
# leave 1st column& row, & make a new square with rest 
# then put the list in that diagonal of new square

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [3]:
np.diagflat([[1,2],[3,4]],k=3) 
# leave 1,2,3 column,row & make a new square with rest 
# then put the list in that diagonal of new square

array([[0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [3]:
np.diagflat([[1,2],[3,4]],k=-1) 
#same operation with opposite direction

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# np.trigonal
(row,column,k=0,dtype)\
below diag all is 1, above diag all is zero 

In [6]:
np.tri(3,5,0,dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [10]:
np.tri(3,3,0,dtype=int)

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [13]:
np.tri(3,3,1,dtype=int)
# leave 1 col,row, make square with rest
# take diagonal
#below diag alll is 1, above diag all is zero 

array([[1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.tri(3,3,2,dtype=int)
#below diag alll is 1, above diag all is zero 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.tri(5,5,2,dtype=int)
#below diag alll is 1, above diag all is zero 

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
a=np.tri(5,7,2,dtype=int)
a[0]

array([1, 1, 1, 0, 0, 0, 0])

In [25]:
for i in a:
    print(i)

[1 1 1 0 0 0 0]
[1 1 1 1 0 0 0]
[1 1 1 1 1 0 0]
[1 1 1 1 1 1 0]
[1 1 1 1 1 1 1]


In [26]:
for i in a:
    for j in i:
        print(j)

1
1
1
0
0
0
0
1
1
1
1
0
0
0
1
1
1
1
1
0
0
1
1
1
1
1
1
0
1
1
1
1
1
1
1


# np.tril
lower triangle

In [28]:
np.tril([[1,2,3],[4,6,4],[7,8,9]])
# triangonal in lower position (put element)
# so, above diag ,all is zero

array([[1, 0, 0],
       [4, 6, 0],
       [7, 8, 9]])

In [30]:
np.tril([[1,2,3],[4,6,4],[7,8,9]],k=1)
# leave 1 col,row then make sqre 
# then  above diag ,all is zero

array([[1, 2, 0],
       [4, 6, 4],
       [7, 8, 9]])

# np.triu
upper triangle

In [32]:
np.triu([[1,2,3],[4,6,4],[7,8,9]],k=0)
# put element in upper position
# below diag , all is zero

array([[1, 2, 3],
       [0, 6, 4],
       [0, 0, 9]])

In [33]:
np.triu([[1,2,3],[4,6,4],[7,8,9]],k=1)
# leave 1 col,row then make sqre 
# then below diag ,all is zero

array([[0, 2, 3],
       [0, 0, 4],
       [0, 0, 0]])

In [36]:
np.triu([[1,2,3],[4,6,4],[7,8,9],[4,2,1]],k=0)

array([[1, 2, 3],
       [0, 6, 4],
       [0, 0, 9],
       [0, 0, 0]])

# np.random.rand
random number generator\
generates uniform distribution(all data btwn 0 to 1)

In [44]:
print("Random number generation (from Uniform distribution)")
np.random.rand(2,3) # uniform distribution

Random number generation (from Uniform distribution)


array([[0.49851181, 0.1378168 , 0.85519018],
       [0.4436241 , 0.6319757 , 0.92761907]])

In [43]:
np.random.rand(2,3,5)

array([[[9.06318224e-01, 3.76162025e-01, 5.29387575e-01, 2.60377800e-04,
         1.95412954e-01],
        [3.44625022e-01, 7.68619181e-01, 9.13017461e-01, 3.59802728e-02,
         1.84947193e-01],
        [8.12971956e-01, 9.41065174e-01, 6.32297744e-01, 4.00321472e-01,
         3.22019381e-01]],

       [[7.89670620e-01, 5.42211402e-01, 3.44240030e-01, 7.01796520e-01,
         4.26286819e-01],
        [4.32261108e-01, 8.96562760e-01, 4.74846021e-01, 2.33228504e-01,
         6.86114327e-01],
        [7.40973847e-01, 1.15476312e-01, 4.39547630e-02, 1.16992942e-01,
         6.87598822e-01]]])

# np.random.randn

In [49]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
np.random.randn(4,3)

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal


array([[ 2.16825702,  0.83180617, -0.54040019],
       [-0.80341423, -0.59219158,  1.05151969],
       [ 1.0231592 , -0.55219792,  0.11564103],
       [-0.75671845, -0.47538005,  0.14325748]])

# np.random.randint

In [51]:
np.random.randint(1,10) 
# give random value,takes int
#start,end,size

7

In [52]:
np.random.randint(1,10,(4,4)) #random in defined shape

array([[6, 7, 1, 3],
       [6, 8, 9, 5],
       [9, 1, 8, 2],
       [3, 7, 2, 5]])

In [53]:
np.random.randint(1,10,(4,4,5))

array([[[8, 3, 6, 8, 3],
        [7, 6, 9, 9, 6],
        [7, 5, 9, 9, 8],
        [7, 7, 9, 5, 9]],

       [[1, 4, 5, 5, 8],
        [9, 6, 5, 1, 1],
        [7, 2, 7, 9, 3],
        [4, 7, 1, 5, 1]],

       [[1, 3, 8, 8, 5],
        [9, 7, 2, 9, 2],
        [6, 4, 2, 7, 8],
        [6, 4, 6, 9, 6]],

       [[1, 1, 8, 8, 4],
        [3, 3, 8, 8, 6],
        [8, 8, 8, 9, 1],
        [7, 5, 1, 6, 7]]])

In [9]:
from numpy.random import randint as ri
a = ri(1,100,30)
a

array([50, 33, 63, 91, 39, 83, 34, 64, 23, 92, 71, 45, 40, 65, 31, 84, 84,
       46, 12, 29, 13, 70, 79, 48, 62, 86,  8, 93, 46, 12])

In [3]:
b = a.reshape(2,3,5)
b

array([[[59, 47, 39, 11, 20],
        [89, 59, 96, 59, 48],
        [41, 76, 76, 62, 38]],

       [[64, 70, 47, 46, 21],
        [73,  1, 13, 78, 94],
        [98, 69, 92, 93, 65]]])

In [4]:
c = a.reshape(6,-19878)
c

array([[59, 47, 39, 11, 20],
       [89, 59, 96, 59, 48],
       [41, 76, 76, 62, 38],
       [64, 70, 47, 46, 21],
       [73,  1, 13, 78, 94],
       [98, 69, 92, 93, 65]])

# np.sort

In [5]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [27 23 78 58 13 64 34 36 97 10]

Here is the sorted vector
 -------------------------------------------------- 
 [10 13 23 27 34 36 58 64 78 97]


In [6]:
ri(1,100,25).reshape(5,5) # Matrix of random interegrs

array([[44, 34, 46, 17, 85],
       [63, 24,  8, 53, 52],
       [67, 35, 41, 80, 19],
       [83, 67, 40, 15, 19],
       [ 1, 73, 94, 57, 27]])

In [7]:
ri(1,100,(5,5)).reshape(5,5) # Matrix of random interegrs

array([[31, 48, 44, 42, 52],
       [85, 76, 58, 71, 77],
       [60, 44, 14, 88, 51],
       [68, 79,  4, 73, 58],
       [68, 65, 18, 52, 56]])

In [8]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 7 31 41 87 88]
 [41 44 46 91 94]
 [ 1  9 25 54 92]
 [26 61 84 88 99]
 [ 6 32 48 79 94]]


array([[88, 31, 87,  7, 41],
       [91, 46, 44, 41, 94],
       [92,  1, 54,  9, 25],
       [99, 84, 61, 26, 88],
       [79, 94, 48,  6, 32]])

In [9]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",)
print(np.sort(M, axis=0, kind='mergesort'))
M


Here is the sorted matrix along each row
 -------------------------------------------------- 

[[ 9  3 31 10  7]
 [37 26 44 14  9]
 [54 36 47 35 30]
 [91 37 51 57 58]
 [92 96 66 82 69]]


array([[92, 26, 44, 10, 58],
       [ 9, 36, 31, 82, 30],
       [37, 37, 66, 35, 69],
       [54,  3, 47, 14,  9],
       [91, 96, 51, 57,  7]])

# max

In [10]:
print("Max of a:", M.max())
M

Max of a: 96


array([[92, 26, 44, 10, 58],
       [ 9, 36, 31, 82, 30],
       [37, 37, 66, 35, 69],
       [54,  3, 47, 14,  9],
       [91, 96, 51, 57,  7]])

In [11]:
print("Max of a location:", M.argmax(axis= 1)) # show-> col wise max element's index 

Max of a location: [0 3 4 0 1]


In [14]:
print("Max of a location:", M.argmax(axis= 0)) # show-> row wise max element's index 

Max of a location: [0 4 2 1 2]


In [15]:
# show the highest index from whole set by counting manually if not consider the axis
print("Max of b location:", b.argmax()) 

Max of b location: 25


In [16]:
b

array([[[59, 47, 39, 11, 20],
        [89, 59, 96, 59, 48],
        [41, 76, 76, 62, 38]],

       [[64, 70, 47, 46, 21],
        [73,  1, 13, 78, 94],
        [98, 69, 92, 93, 65]]])

In [76]:
print("Max of a location:", M.argmax(axis= 0 ))

Max of a location: [3 4 0 4 1]


# Indexing & slicing

In [18]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# 7th index
arr[7]

7

In [23]:
# from 3rd to 5th index
arr[3:6:2]

array([3, 5])

In [24]:
#up to 4th index
arr[:4]

array([0, 1, 2, 3])

In [26]:
# from the last backwards
arr[-1:7:-1]

array([10,  9,  8])

In [30]:
# three element from the backwards
arr[-1:-6:2]

array([], dtype=int32)

In [32]:
# Elements at 2nd, 4th, and 9th index are:
arr = np.arange(0,21,2)
arr[[2,4,9]]

array([ 4,  8, 18])

In [10]:
x=np.array(ri(10,100,45)).reshape(3,5,3)
x

array([[[76, 80, 42],
        [62, 62, 38],
        [45, 22, 89],
        [37, 27, 77],
        [89, 52, 33]],

       [[19, 34, 47],
        [90, 88, 97],
        [55, 17, 28],
        [80, 56, 69],
        [55, 40, 94]],

       [[45, 58, 13],
        [91, 78, 79],
        [60, 31, 59],
        [62, 55, 34],
        [98, 75, 15]]])

In [11]:
x[1]

array([[19, 34, 47],
       [90, 88, 97],
       [55, 17, 28],
       [80, 56, 69],
       [55, 40, 94]])

In [12]:
#2nd row 
x[1][1]

array([90, 88, 97])

In [13]:
x[1][1][0]

90

In [14]:
x

array([[[76, 80, 42],
        [62, 62, 38],
        [45, 22, 89],
        [37, 27, 77],
        [89, 52, 33]],

       [[19, 34, 47],
        [90, 88, 97],
        [55, 17, 28],
        [80, 56, 69],
        [55, 40, 94]],

       [[45, 58, 13],
        [91, 78, 79],
        [60, 31, 59],
        [62, 55, 34],
        [98, 75, 15]]])

In [15]:
# 1st->middle column
x[0][:,1]

array([80, 62, 22, 27, 52])

In [16]:
# 1st 2 rows from every dimension
x[0][0:2],x[1][0:2],x[2][0:2]

(array([[76, 80, 42],
        [62, 62, 38]]),
 array([[19, 34, 47],
        [90, 88, 97]]),
 array([[45, 58, 13],
        [91, 78, 79]]))

In [21]:
x[0:3][:,0:2]

array([[[76, 80, 42],
        [62, 62, 38]],

       [[19, 34, 47],
        [90, 88, 97]],

       [[45, 58, 13],
        [91, 78, 79]]])

In [22]:
x[0:3,[0,1]]

array([[[76, 80, 42],
        [62, 62, 38]],

       [[19, 34, 47],
        [90, 88, 97]],

       [[45, 58, 13],
        [91, 78, 79]]])

In [23]:
for i in range(3):
    print(x[i][:2,:])

[[76 80 42]
 [62 62 38]]
[[19 34 47]
 [90 88 97]]
[[45 58 13]
 [91 78 79]]


# subsetting

In [27]:
a=np.array(ri(10,100,15)).reshape(3,5)
a>50

array([[False, False, False, False, False],
       [ True, False,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [28]:
a[a>50]

array([55, 82, 59, 86, 51, 82, 59, 64])

In [29]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
# sliced
mat[:2][:,:2]

array([[11, 12],
       [21, 22]])

In [31]:
mat

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [45]:
mat[:2][:,:2]

array([[11, 12],
       [21, 22]])

In [78]:
mat1=mat[:2][:,:2]
mat1[0][0]=100
mat1

array([[100,  12],
       [ 21,  22]])

In [80]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
mat1*mat2  # one to one multiplication

array([[12, 12,  8],
       [15, 18,  4],
       [36,  3, 12]])

In [81]:
mat1@mat2   # matrix multiplication

array([[41, 55, 59],
       [34, 29, 34],
       [59, 43, 50]])

In [84]:
mat1+mat2  # addition

array([[ 8,  7,  9],
       [ 8, 11,  4],
       [13,  4,  7]])

In [83]:
mat1/0   # division

C:\Users\damrs\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [85]:
100+mat1

array([[106, 104, 101],
       [103, 102, 102],
       [104, 103, 104]])

In [86]:
mat1**3  # power

array([[216,  64,   1],
       [ 27,   8,   8],
       [ 64,  27,  64]], dtype=int32)

In [88]:
pow(mat1,3) # another way

array([[216,  64,   1],
       [ 27,   8,   8],
       [ 64,  27,  64]], dtype=int32)

# broadcsting

In [89]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [93]:
start=np.zeros((4,4))
start=start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [95]:
# add rows addition
add_row=np.array([1,0,5,8])
start+add_row

array([[101., 100., 105., 108.],
       [101., 100., 105., 108.],
       [101., 100., 105., 108.],
       [101., 100., 105., 108.]])

In [101]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [102]:
add_cols+start

array([[100., 100., 100., 100.],
       [101., 101., 101., 101.],
       [102., 102., 102., 102.],
       [103., 103., 103., 103.]])

In [103]:
# square root
np.sqrt(mat1)

array([[2.44948974, 2.        , 1.        ],
       [1.73205081, 1.41421356, 1.41421356],
       [2.        , 1.73205081, 2.        ]])

In [105]:
#exponential
np.exp(mat1)

array([[403.42879349,  54.59815003,   2.71828183],
       [ 20.08553692,   7.3890561 ,   7.3890561 ],
       [ 54.59815003,  20.08553692,  54.59815003]])

In [106]:
#log
np.log10(mat1)

array([[0.77815125, 0.60205999, 0.        ],
       [0.47712125, 0.30103   , 0.30103   ],
       [0.60205999, 0.47712125, 0.60205999]])

In [107]:
# modulo function
np.fmod(mat1,mat2)

array([[0, 1, 1],
       [3, 2, 0],
       [4, 0, 1]], dtype=int32)

In [108]:
# or,
mat1%mat2

array([[0, 1, 1],
       [3, 2, 0],
       [4, 0, 1]], dtype=int32)

In [53]:
# print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)
A = np.linspace(0,12*np.pi,1001)
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])